"""empty message

Revision ID: 825f15c86b90
Revises: 1c869a2dd2d1
Create Date: 2020-07-22 12:38:58.009248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '825f15c86b90'
down_revision = '1c869a2dd2d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('date', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'date')
    op.drop_table('comments')
    # ### end Alembic commands ###
